config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :items do 
     resources :products
  end 

  resources :specials

  resources :aboutus, only: [:index]

  resources :termsofuse, only: [:index]

  resources :contacts

  get '/generalpages/:id', to: 'generalpages#aboutus'

  root 'items#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/contact.rb
class Contact < ActiveRecord::Base

	belongs_to :user

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

	before_action :find_contact, only: [:create, :edit, :update, :delete]

	def index
		@contacts = Contact.all.order("created_at DESC")
	end

	def show
	end

	def new
		@contact = current_user.contacts.build
	end

	def create
		@contact = current_user.contacts.build(contact_params)
		if @contact.save
			redirect_to @contact
		else
			render 'new'
		end 
	end

	def edit
	end

	def update
		if @contact.update(contact_params)
			redirect_to @contact
		else 
			render 'edit'
		end
	end

	def destroy
		@contact.destroy
		redirect_to @contact
	end

	private

	def find_contact
		@contact = Contact.find(params[:id])
	end

	def contact_params
		params.require(:contact).permit(:phone, :email, :website, :address)
	end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	before_action :find_contact, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index 
		@contacts = Contact.all.order("created_at DESC")
	end

	def show
	end

	def new
		@contact = current_user.contact.build
	end

	def create
		@contact = current_user.contact.build(contact_params)
		if @contact.save
			redirect_to @contact
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @contact.update(contact_params)
			redirect_to @contact
		else 
			render 'edit'
		end
	end

	def destroy
		@contact.destroy
		redirect_to @contact
	end

	private

	def find_contact
		@contact = Contact.find(params[:id])
	end

	def contact_params
		params.require(:contact).permit(:phone, :email, :website, :address)
	end	


end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for @contact do |f| %>
	<p><%= f.label :phone %></p>
	<%= f.text_field :phone %>
	<p><%= f.label :email %></p>
	<%= f.text_field :email %>
	<p><%= f.label :website %></p>
	<%= f.text_field :website %>
	<p><%= f.label :address %></p>
	<%= f.text_field :address %>

	<p><%= f.submit %></p>
<% end %>

app/views/contacts/edit.html.erb
<h2>Edit Contact</h2>

<%= render 'form' %>

app/views/contacts/index.html.erb
<h2 class="title">Contact Us</h2>

<% if user_signed_in? %>
	<%= link_to "Upload Detail", new_contact_path %></h4>
<% end %>

<% @contacts.each do |contact| %>

	<h3>Opening times</h3>
	Monday to Friday - 9am to 3pm

	<h3>Call us on:</h3>
	<%= contact.phone %>
	 
	<h3>Email:</h3>
	<%= contact.email %>
	 
	<h3>Web Site:</h3>
	<div class="contact_link">
		<%= link_to contact.website, contact.website, :target => "_blank" %> 
	</div>

	<h3>Our Address is:</h3>
	167 Farnham Road,
	Slough,
	Berkshire,
	SL1 4XP
	<% if user_signed_in? %>
		<p><%= link_to 'Edit', edit_contact_path(contact) %>
		<%= link_to 'Delete', contact_path(contact), method: :delete, data: {confirm: "Are you sure?"} %></p>
	<% end %>
<% end %>


<script src='https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCOHFWJpiCfSkg88OIl3DDW4lHYtrjmQfg'></script><div style='overflow:hidden;height:400px;width:520px;'><div id='gmap_canvas' style='height:400px;width:520px;'></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style></div> <a href='https://add-map.org/'>add google map</a> <script type='text/javascript' src='https://embedmaps.com/google-maps-authorization/script.js?id=970b15fd21dea7b09e3e705a441b820ec5cf9bb0'></script><script type='text/javascript'>function init_map(){var myOptions = {zoom:12,center:new google.maps.LatLng(51.5248321,-0.6153928999999607),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById('gmap_canvas'), myOptions);marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(51.5248321,-0.6153928999999607)});infowindow = new google.maps.InfoWindow({content:'<strong>Home Makers </strong><br>Farnham Road<br>SL1 4XP Slough<br>'});google.maps.event.addListener(marker, 'click', function(){infowindow.open(map,marker);});infowindow.open(map,marker);}google.maps.event.addDomListener(window, 'load', init_map);</script>

app/views/contacts/new.html.erb
<h2>Upload Contact</h2>

<%= render 'form' %>

app/views/contacts/show.html.erb
<%= link_to "Contact Us", contacts_path %>