config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :items do 
     resources :products
  end 

  resources :specials

  resources :aboutus, only: [:index]

  resources :termsofuse, only: [:index]

  resources :contacts

  get '/generalpages/:id', to: 'generalpages#aboutus'

  root 'items#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/special.rb
class Special < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  	validates :title, :presence => true, :length => {:maximum => 70}
  	validates :price, :presence => true
  	validates :description, :presence => true
  	validates :image, :presence => true
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
	
	before_action :find_special, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index 
		@specials = Special.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
	end

	def show
	end

	def new
		@special = current_user.specials.build
	end

	def create
		@special = current_user.specials.build(special_params)

		if @special.save
			flash[:notice] = "Special Offer Uploaded"
			redirect_to @special
		else
			flash[:notice] = "Please fill in all fields"
			render 'new'
		end
	end

	def edit
	end

	def update
		if @special.update(special_params)
			flash[:notice] = "Special offer updated"
			redirect_to @special
		else
			flash[:notice] = "Please fill in all fields"
			render 'edit'
		end
	end

	def destroy
		flash[:notice] = "Special offer deleted"
		@special.destroy
		redirect_to @special
	end

	private

	def find_special
		@special = Special.find(params[:id])
	end

	def special_params
		params.require(:special).permit(:title, :description, :price, :image)
	end
end

app/views/specials/_form.html.erb
<%= form_for @special do |f| %>
	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>
	<p><%= f.label :description %></p>
	<p><%= f.text_area :description %></p>
	<p><%= f.label :price %></p>
	<p><%= f.number_field :price %></p>
	<p><%= f.label :image %></p>
	<%= f.file_field :image %>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/specials/edit.html.erb
<h2>Edit Special Deal</h2>

<%= render 'form' %>

app/views/specials/index.html.erb
<div class="special_header", id="clearfix">
	<h2 id="clearfix">Special Offers</h2>
	<% if user_signed_in? %>
		<div class="headerlink">
			<%= link_to "Upload Special Offer", new_special_path %>
		</div>
	<% end %>
</div>


<% @specials.each do |special| %>
	<div class="special_content", id="clearfix">
		<h3><%= special.title.titleize %></h3>
		<%= image_tag special.image.url(:small) %>
		<p class="special_description"><%= special.description %></p>
		<p><%= number_to_currency(special.price, :precision => 2, :unit => "£") %></p>
		<% if user_signed_in? %>
			<div class="edit_delete", id="clearfix">
				<%= link_to "Edit", edit_special_path(special) %>
				<%= link_to "Delete", special_path(special), method: :delete, data: {confirm: "Are you sure?"} %>
			</div>
		<% end %>
	</div>
<% end %>

<div class="paginate", id="clearfix">
	<p id="clearfix"><%= will_paginate @product, inner_window:1, outer_window:0 %></p>
</div>

app/views/specials/new.html.erb
<h2>Post A Special</h2>

<% if user_signed_in? %>
	<%= render 'form' %>
<% end %>

app/views/specials/show.html.erb
<%= link_to "Special Offers", specials_path %>