config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :items do 
     resources :products
  end 

  resources :specials

  resources :aboutus, only: [:index]

  resources :termsofuse, only: [:index]

  resources :contacts

  get '/generalpages/:id', to: 'generalpages#aboutus'

  root 'items#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/item.rb
class Item < ActiveRecord::Base

	has_many :products
	belongs_to :user
	belongs_to :category

	has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/	

  	validates :title, :presence => true, :length => {:maximum => 25}
  	validates :image, :presence => true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_action :find_item, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if params[:category].blank?
			@items = Item.all.order("created_at DESC")
		else 
			@category_id = Category.find_by(name: params[:category]).id
			@items = Item.where(category_id: @category_id).order("created_at DESC")
		end
	end

	def show
		@products = Product.where(item_id: @item)
	end

	def new
		@item = current_user.items.build
	end

	def create
		@item = current_user.items.build(params_item)
		if @item.save 
			flash[:notice] = "Category created"
			redirect_to root_path
		else 
			flash[:notice] = "Please Enter all fields"
			render 'new'
		end
	end

	def edit
	end

	def update
		if @item.update(params_item)
			flash[:notice] = "Category Changed"
			redirect_to root_path
		else 
			flash[:alert] = "Make sure to compete all sections"
			render 'edit'
		end
	end

	def destroy
		flash[:notice] = "Category deleted"
		@item.destroy
		redirect_to root_path
	end

	private

	def find_item
		@item = Item.find(params[:id])
	end

	def params_item
		params.require(:item).permit(:title, :image, :category_id)
	end

end

app/views/items/_form.html.erb
<div class="form">
	<%= form_for @item do |f| %>
		<%= f.label :category %>
		<%= f.collection_select :category_id, Category.all, :id, :name, {prompt: "Choose a Category"} %>
		<p><%= f.label :title %></p>
		<%= f.text_field :title %>
		<p><%= f.label :image %></p>
		<%= f.file_field :image %>
		<%= f.submit %>
	<% end %>
</div>

app/views/items/edit.html.erb
<h2>Edit Item</h2>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="category_links", id="clearfix">
	<%= link_to "All Products", root_path, class: "all_product" %>
		<!--<button class="category_button">Categories</button>-->
			<% Category.all.each do |category| %>
			<!-- <ul id="clearfix"> -->
				<%= link_to category.name, items_path(category: category.name) %>
			<% end %>
</div>

<% @items.each do |item| %>
	<div class="index_item", id="clearfix">
		<%= link_to (image_tag item.image.url(:small)), item, class:"index_image"%>
		<h3><%= link_to item.title, item %></h3>
	</div>
<% end %>

app/views/items/new.html.erb
<h2>Create New Category</h2>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="show_header" id="clearfix">
	<h2 class="show_title"><%= @item.title %></h2>
	<% if user_signed_in? %>
		<div class="show_header_links">
			<%# link_to "Upload Product", new_item_product_path(@item), class:"buttons" %>
			<%= link_to "Edit", edit_item_path(@item), class:"buttons" %> 
			<%= link_to "Delete", item_path(@item), method: :delete, data: {confirm:"Are you sure"}, class:"buttons" %>
		</div>
	<% end %>
</div>

<% if user_signed_in? %>
	<h3>Upload Product</h3>
	<%= render 'products/form' %>
<% end %>

<div class="product", id="clearfix">
	<% @products.each do |product| %>
		<div class="product_content", id="clearfix">
			<h3><%= product.title.titleize %></h3>
			<%= image_tag product.image.url(:small), class:"index_image" %>
			<p>Description: <%= product.description %></p>
			<div class="product_numbers", id="clearfix">
				<p class="currency", id="clearfix"><%= number_to_currency(product.price, :precision => 2, :unit => "£") %>	
				</p>
				<p class="stock", id="clearfix">Stock: <%= product.stock %></p>
			</div>
			<% if user_signed_in? %>
			<div class="edit_delete", id="clearfix">
				<%= link_to "Edit", edit_item_product_path(product.item, product) %>
				<%= link_to "Delete", [product.item, product], method: :delete, data: {confirm:"Are you sure?"} %>
			</div>
			<% end %>
		</div>
	<% end %>
</div>

<%# will_paginate @product %>