config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users

  resources :items do 
     resources :products
  end 

  resources :specials

  resources :aboutus, only: [:index]

  resources :termsofuse, only: [:index]

  resources :contacts

  get '/generalpages/:id', to: 'generalpages#aboutus'

  root 'items#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeMakers</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>

<header id="clearfix">
	<div class="wrapper_slim">
		<h1><%= link_to "Slough Furniture Project", root_path %></h1>
		<div>
		<button class="main_menu"><i class="fa fa-align-justify"></i></button>
		</div>

		<div class="header_links">
			<% if user_signed_in? %>
			<%= link_to "Create Category", new_item_path %>
			<% end %>
			<%= link_to "Contact Us", contacts_path %>
			<%= link_to "About Us", aboutus_path %>
			<%= link_to "Special Offers", specials_path %>
			<% if user_signed_in? %>
			<%= link_to "Sign Out", destroy_user_session_path, method: :delete %> 
			<% end %>
		</div>
	</div>
</header>

<div class="wrapper_slim">
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
</div>


<div class="wrapper_slim" id="clearfix">
	<%= yield %>
</div>

<footer class="wrapper_slim", id="clearfix">
	<p class="footer_content">&copy;Slough Furniture Project 2016 - <%= Date.today.year %> |
		<%= link_to "Terms Of Use", termsofuse_index_path %>
		| Registered Charity No 1152062 | <a href="http://www.easyfundraising.org.uk" target="_blank">www.easyfundraising.org.uk</a><p><span>Created by Scott Berry &amp; donated to Slough Furniture Project</span></p>
	</p>
</footer>
</body>
</html>